const statusLU = [
  { label: "NEW", value: "NEW" },
  { label: "OPEN", value: "OPEN" },
  { label: "CLOSED", value: "CLOSED" },
  { label: "ALL", value: "ALL" },
  { label: "SPAM", value: "SPAM" },
];
const messageConstants = {
  SUCCESS: "success",
  ERROR: "error",
  WARNING: "warning",
  INFO: "info",
  LOADING: "loading",
};

const PREMIUMSTATUSLIST = [
  { descItem: "AC", shortDesc: "Auto Cover", longDesc: "Auto Cover Period" },
  { descItem: "AF", shortDesc: "Foreclose", longDesc: "Foreclosure" },
  { descItem: "AP", shortDesc: "Ann Paying", longDesc: "Annuity in Payment" },
  {
    descItem: "CD",
    shortDesc: "CF DOB Chg",
    longDesc: "Cancelld frm Inception DOB chg",
  },
  { descItem: "CF", shortDesc: "CFI", longDesc: "Cancelled from Inception" },
  {
    descItem: "CR",
    shortDesc: "Clm-Regstd",
    longDesc: "Health Claim Premium Status",
  },
  { descItem: "DC", shortDesc: "Declined", longDesc: "Declined" },
  {
    descItem: "DF",
    shortDesc: "Disc Forc",
    longDesc: "Discontinuance Foreclose",
  },
  { descItem: "DH", shortDesc: "Deceased", longDesc: "Deceased" },
  {
    descItem: "DI",
    shortDesc: "Dth Disc I",
    longDesc: "Dth-Discontinued Invalid",
  },
  {
    descItem: "DS",
    shortDesc: "Er Sur Reg",
    longDesc: "Early Surrendr Registered",
  },
  { descItem: "DU", shortDesc: "Discont", longDesc: "Policy Discontinued" },
  { descItem: "EL", shortDesc: "Extd Life", longDesc: "Extended Maturity" },
  { descItem: "ET", shortDesc: "ETI", longDesc: "Extended Term Insurance" },
  { descItem: "EX", shortDesc: "Expired", longDesc: "Expired" },
  {
    descItem: "FL",
    shortDesc: "Free Look",
    longDesc: "Free Look Cancellation",
  },
  { descItem: "FP", shortDesc: "Fully Paid", longDesc: "Fully Paid" },
  {
    descItem: "FR",
    shortDesc: "FL Regstr",
    longDesc: "Free Look Cancel Register",
  },
  { descItem: "FU", shortDesc: "FP Death", longDesc: "FullyPaid Death" },
  {
    descItem: "HA",
    shortDesc: "Prem Holdy",
    longDesc: "Premium Holiday - Auto",
  },
  { descItem: "HC", shortDesc: "Health Clm", longDesc: "Health Claim" },
  {
    descItem: "HP",
    shortDesc: "PH RestPnd",
    longDesc: "PH Reinstatement Pending",
  },
  { descItem: "LA", shortDesc: "Lapsed", longDesc: "Lapsed" },
  { descItem: "LM", shortDesc: "Lapse Mat", longDesc: "Lapsed Maturity" },
  { descItem: "MA", shortDesc: "Matured", longDesc: "Matured" },
  { descItem: "MD", shortDesc: "Mat Death", longDesc: "Maturity-Death" },
  {
    descItem: "MO",
    shortDesc: "MO",
    longDesc: "Maturity-Settlmnt (No admin)",
  },
  { descItem: "MS", shortDesc: "Mat Stl", longDesc: "Maturity-Settlmnt opt" },
  { descItem: "MX", shortDesc: "Setlmt-End", longDesc: "Setlmt-End" },
  {
    descItem: "NF",
    shortDesc: "NF Surr",
    longDesc: "Non-Forfeiture Surrendered",
  },
  { descItem: "PM", shortDesc: "Prm Matury", longDesc: "Premium Maturity" },
  { descItem: "PO", shortDesc: "Postpone", longDesc: "Contract Postponed" },
  { descItem: "PP", shortDesc: "Prm Paying", longDesc: "Premium Paying" },
  { descItem: "PS", shortDesc: "Proposal", longDesc: "Proposal" },
  { descItem: "PU", shortDesc: "Paid-up", longDesc: "Made Paid-up" },
  {
    descItem: "RC",
    shortDesc: "Repudiate",
    longDesc: "Repudiate Death Claim",
  },
  { descItem: "RP", shortDesc: "Red Paidup", longDesc: "Reduced Paid-up" },
  {
    descItem: "RS",
    shortDesc: "Repd Setlm",
    longDesc: "Repudiation Settlement Option",
  },
  {
    descItem: "S",
    shortDesc: "Suspended",
    longDesc: "Suspended Pending Transaction",
  },
  {
    descItem: "SD",
    shortDesc: "Er Sr Appv",
    longDesc: "Early Surrender Approval",
  },
  { descItem: "SP", shortDesc: "Single Prm", longDesc: "Single Premium" },
  { descItem: "SR", shortDesc: "Surr Reg", longDesc: "Surrender Register" },
  { descItem: "SU", shortDesc: "Surrender", longDesc: "Fully Surrendered" },
  {
    descItem: "TM",
    shortDesc: "Terminate",
    longDesc: "Termination Health Claim",
  },
  {
    descItem: "UD",
    shortDesc: "Unpaid Dis",
    longDesc: "Unpaid Discontinued",
  },
  { descItem: "VA", shortDesc: "Vest Appr", longDesc: "Vesting Approval" },
  { descItem: "VP", shortDesc: "Vest pendg", longDesc: "Vesting Pending" },
  { descItem: "VR", shortDesc: "Vest Reg", longDesc: "Vesting Registered" },
  { descItem: "WD", shortDesc: "Withdrawn", longDesc: "Withdrawn" },
  { descItem: "WV", shortDesc: "WvrofPrem", longDesc: "Waiver of Premium" },
];

const RIDERCODEMAPPING = {
  ADBR: "Accidental Death Rider",
  ADRB: "Accidental Death Rider",
  ADTR: "Accidental Death Benefit Rider",
  ATPD: "Accidental TPD Rider",
  CIBR: "Critical Illness (Core) Rider",
  CITR: "Accelerated CI Benefit Rider",
  EADB: "Accidental Death Rider",
  ECIB: "Critical Illness (Core) Rider",
  ELGR: "Life Guardian Rider",
  ETPD: "Accidental TPD Rider",
  ETRM: "Term Assurance Rider",
  E06P: "Premium Waiver Benefit Rider",
  E07P: "Premium Waiver Benefit Rider",
  E08P: "Premium Waiver Benefit Rider",
  E1TP: "Accidental TPD Rider",
  E11M: "GC Saral Term Benefit Rider",
  E14M: "Term Assurance Rider",
  E16A: "Accidental Death Benefit Rider",
  E16M: "Term Assurance Rider",
  E17A: "Accidental Death Benefit Rider",
  E17C: "Critical Illness (Core) Rider",
  E17M: "Term Assurance Rider",
  E18T: "Accidental TPD Rider",
  E19T: "Accidental TPD Rider",
  E2TP: "Accidental TPD Rider",
  E20T: "Accidental TPD Rider",
  E21T: "Accidental TPD Rider",
  E23A: "Accidental Death Rider",
  E23C: "Critical Illness (Core) Rider",
  E23D: "Accidental TPD Rider",
  E23M: "Term Assurance Rider",
  E23P: "Premium Waiver Benefit Rider",
  E24P: "Premium Waiver Benefit Rider",
  E24T: "Term Assurance Rider",
  E25P: "Premium Waiver Benefit Rider",
  E25T: "Term Assurance Rider",
  E26T: "Accidental TPD Rider",
  E29A: "Accidental Death Rider",
  E29C: "Critical Illness (Core) Rider",
  E29M: "Term Assurance Rider",
  E29P: "Premium Waiver Benefit Rider",
  E29T: "Accidental TPD Rider",
  E29W: "Life Guardian Rider",
  E3TP: "Accidental TPD Rider",
  E30P: "Premium Waiver Benefit Rider",
  E30T: "Term Assurance Rider",
  E31P: "Premium Waiver Benefit Rider",
  E31T: "Term Assurance Rider",
  E32A: "Accidental Death Benefit Rider",
  E32M: "Term Assurance Rider",
  E33A: "Accidental Death Benefit Rider",
  E33C: "Critical Illness (Core) Rider",
  E33M: "Term Assurance Rider",
  E35A: "Accidental Death Benefit Rider",
  E35T: "Accidental TPD Rider",
  E36A: "Accidental Death Rider",
  E36T: "Accidental TPD Rider",
  E37C: "Critical Illness (Core) Rider",
  E37M: "Term Assurance Rider",
  E38A: "Accidental Death Rider",
  E38T: "Accidental TPD Rider",
  E4TP: "Accidental TPD Rider",
  E42A: "E42 - Accidental Death Rider",
  E42T: "E42 - Accidental TPD Rider",
  E46A: "E46 - Accidental Death Rider",
  E46T: "E46 - Accidental TPD Rider",
  E47A: "E47 - Accidental Death Rider",
  E47T: "E47 - Accidental TPD Rider",
  E49A: "Accidental Death Rider",
  E49T: "Accidental TPD Rider",
  E54A: "Accidental Death Rider",
  E54T: "Accidental TPD Rider",
  E67A: "E67 - Accidental Death Rider",
  E67T: "E67 - Accidental TPD Rider",
  E68A: "E68 - Accidental Death Rider",
  E68T: "E68 - Accidental TPD Rider",
  E69A: "E69 - Accidental Death Rider",
  E69T: "E69 - Accidental TPD Rider",
  E7TM: "GC Saral Term Benefit Rider",
  E8TM: "GC Saral Term Benefit Rider",
  E9TP: "Accidental TPD Rider",
  FA1P: "Premium Waiver Benefit Rider",
  NADB: "Accidental Death Rider",
  NATP: "Accidental TPD Rider",
  RADB: "Accidental Death Rider",
  RATP: "Accidental TPD Rider",
  TPDR: "Accidental TPD Rider",
  TRMR: "Term Assurance Rider",
  T07A: "Accidental Death Rider",
  T08A: "Accidental Death Rider",
  T09A: "Accidental Death Rider",
  T09J: "Accidental Death and TPD Rider",
  T10A: "Accidental Death Rider",
  T10J: "Accidental Death and TPD Rider",
  T11A: "Accidental Death Rider",
  T11J: "Accidental Death and TPD Rider",
  T18A: "Accidental Death Rider",
  T19A: "Accidental Death Rider",
  T2AD: "Accidental Death Benefit Rider",
  T2CI: "Accelerated CI Benefit Rider",
  T20A: "Accidental Death Rider",
  T21T: "Accidental TPD Rider",
  T22T: "Accidental TPD Rider",
  T23A: "Accidental Death Rider",
  T23T: "Accidental TPD Rider",
  T24C: "Critical Illness (Core) Rider",
  T24T: "Accidental TPD Rider",
  T25A: "Accidental Death Rider",
  T25C: "Critical Illness (Core) Rider",
  T25T: "Accidental TPD Rider",
  T3AD: "Accidental Death Benefit Rider",
  T3CI: "Accelerated CI Benefit Rider",
  T31A: "Accidental Death Rider",
  T37A: "Accidental Death Rider",
  T58A: "Accidental Death Rider",
  T6AD: "Accidental Death Benefit Rider",
  T6CI: "Accelerated CI Benefit Rider",
  T6TM: "Term Assurance Rider",
  T6TP: "Accidental TPD Rider",
  UADR: "Accidental Death Rider",
  UADS: "Accidental Death Rider",
  UAD2: "Accidental Death Rider",
  UCIR: "Critical Illness (Core) Rider",
  UCIS: "Critical Illness (Core) Rider",
  UCI2: "Critical Illness (Core) Rider",
  UTDR: "Accidental TPD Rider",
  UTDS: "Accidental TPD Rider",
  UTD2: "Accidental TPD Rider",
  UTMR: "Term Assurance Rider",
  UTM2: "Term Assurance Rider",
  UWOR: "Life Guardian Rider",
  UWO2: "Life Guardian Rider",
  U10A: "Accidental Death Rider",
  U11A: "Accidental Death Rider",
  U11C: "Critical Illness (Core) Rider",
  U11T: "Accidental TPD Rider",
  U11W: "Life Guardian Rider",
  U13M: "Term Assurance Rider",
  U17A: "Accidental Death Rider",
  U17C: "Critical Illness (Core) Rider",
  U17F: "Family Benefit Rider",
  U17T: "Accidental TPD Rider",
  U17V: "Premium Waiver Benefit Rider",
  U17W: "Life Guardian Rider",
  U2AD: "Accidental Death Rider",
  U21A: "Accidental Death Rider",
  U22A: "Accidental Death Rider",
  U22C: "Critical Illness (Core) Rider",
  U22T: "Accidental TPD Rider",
  U22W: "Life Guardian Rider",
  U23A: "Accidental Death Rider",
  U23C: "Critical Illness (Core) Rider",
  U23T: "Accidental TPD Rider",
  U23W: "Life Guardian Rider",
  U24A: "Accidental Death Rider",
  U25E: "EIC Rider",
  U26A: "Accidental Death Rider",
  U26T: "Accidental TPD Rider",
  U27A: "Accidental Death Rider",
  U28A: "Accidental Death Rider",
  U28T: "Accidental TPD Rider",
  U29A: "Accidental Death Rider",
  U30A: "Accidental Death Rider",
  U30C: "Critical Illness (Core) Rider",
  U30T: "Accidental TPD Rider",
  U30W: "Life Guardian Rider",
  U31A: "Accidental Death Rider",
  U31T: "Accidental TPD Rider",
  U33A: "Accidental Death Rider",
  U33T: "Accidental TPD Rider",
  U34A: "Accidental Death Rider",
  U34T: "Accidental TPD Rider",
  U35A: "Accidental Death Rider",
  U35T: "Accidental TPD Rider",
  U36A: "Accidental Death Rider",
  U36T: "Accidental TPD Rider",
  U37A: "Accidental Death Rider",
  U37T: "Accidental TPD Rider",
  U38A: "Accidental Death Rider",
  U38T: "Accidental TPD Rider",
  U39A: "Accidental Death Rider",
  U39T: "Accidental TPD Rider",
  U40A: "Accidental Death Rider",
  U40T: "Accidental TPD Rider",
  U41A: "Accidental Death Rider",
  U41T: "Accidental TPD Rider",
  U42A: "Accidental Death Rider",
  U42C: "Critical Illness (Core) Rider",
  U42T: "Accidental TPD Rider",
  U42W: "Life Guardian Rider",
  U43A: "Accidental Death Rider",
  U43T: "Accidental TPD Rider",
  U44A: "Accidental Death Rider",
  U51A: "Accidental Death Rider",
  U51T: "Accidental TPD Rider",
  U9AD: "Accidental Death Rider",
  WOPR: "Life Guardian Rider",
  EA6W: "GC Long Term Income Plan_Opt 2",
  EB2W: "GC Assrd Wlth Pln-Opt 2 Waiver",
  EB7W: "GC New Assure Plus:Opt2 Waiver",
  EC6W: "GC Long Term Income Plan_Opt 2",
  EWOP: "WOP on Disability",
  E1WP: "Waiver of Premium",
  E10A: "Accidental Death Benefit",
  E11A: "GC Accidental Death Benefit",
  E11W: "GC Premium Waiver Benefit",
  E14A: "Accidental Death Benefit",
  E14E: "GC Income Plus",
  E14W: "Waiver of Premium",
  E15E: "GC Income Plus Single Premium",
  E16W: "Waiver of Premium",
  E17W: "Waiver of Premium",
  E18W: "Waiver of Premium",
  E20W: "Waiver of Premium",
  E23W: "WOP on Disability",
  E24A: "Future Saral Anand - ADB",
  E24N: "Future Saral Anand - Endowment",
  E25A: "Future Saral Anand (Simpl)ADB",
  E25N: "Future Saral Anand (simpl)Endw",
  E26A: "Accidental Death Benefit",
  E26W: "Waiver of Premium",
  E29D: "WOP on Disability",
  E3WP: "Waiver of Premium",
  E30A: "Future Saral Anand (Simpl)ADB",
  E30N: "Future Saral Anand (simpl)Endw",
  E31A: "Future Saral Anand - ADB",
  E31N: "Future Saral Anand - Endowment",
  E32W: "Waiver of Premium",
  E33W: "Waiver of Premium",
  E37A: "Accidental Death Benefit",
  E37W: "GC Premium Waiver Benefit",
  E57W: "GC New Assure Plus:Opt2 Waiver",
  E64W: "GC Assrd Wlth Pln-Opt 2 Waiver",
  E7AD: "Future Saral Anand - ADB",
  E7EN: "Future Saral Anand - Endowment",
  E78W: "GC New Assure Plus:Opt2 Waiver",
  E8AD: "Future Saral Anand (Simpl)ADB",
  E8EN: "Future Saral Anand (simpl)Endw",
  E81W: "GC Assrd Wlth Pln-Opt 2 Waiver",
  E84W: "GC Assrd Wlth Pln-Opt 2 Waiver",
  E9AD: "Accidental Death Benefit",
  E9WP: "Waiver of Premium",
  E98W: "GC Long Term Income Plan_Opt 2",
  T241: "Critical Illness - Angioplasty",
  T251: "Critical Illness - Angioplasty",
  U15A: "Accidental Death Benefit",
  U21I: "GC Nivesh Plus - Investment",
  U36W: "Waiver of Premium",
  U40W: "Waiver of Premium",
  U49W: "Waiver of Premium",
  WOPD: "WOP on Disability",
};
const POLICYSTATUSLIST = [
  { descItem: "EL", shortDesc: "Extd Life", longDesc: "Extended Maturity" },
  { descItem: "EX", shortDesc: "Expiry", longDesc: "Expiry" },
  {
    descItem: "FA",
    shortDesc: "FP DthAppv",
    longDesc: "FullyPaid Death Approval",
  },
  {
    descItem: "FD",
    shortDesc: "FP Dth Reg",
    longDesc: "FullyPaid Death Register",
  },
  {
    descItem: "FL",
    shortDesc: "Free Look",
    longDesc: "Free Look Cancellation",
  },
  {
    descItem: "FR",
    shortDesc: "FL Regstr",
    longDesc: "Free Look Cancel Register",
  },
  { descItem: "HC", shortDesc: "Health Clm", longDesc: "Health Claim" },
  {
    descItem: "HP",
    shortDesc: "PH RestPnd",
    longDesc: "PH Reinstatement Pending",
  },
  { descItem: "IF", shortDesc: "In Force", longDesc: "In Force" },
  { descItem: "LA", shortDesc: "Lapsed", longDesc: "Contract Lapsed" },
  { descItem: "LM", shortDesc: "Lapsed Mat", longDesc: "Lapsed Maturity" },
  { descItem: "MA", shortDesc: "Matured", longDesc: "Contract Matured" },
  { descItem: "MD", shortDesc: "Mat Death", longDesc: "Maturity Death" },
  {
    descItem: "MO",
    shortDesc: "MO",
    longDesc: "Maturity-Settlmnt (No admin)",
  },
  {
    descItem: "MP",
    shortDesc: "Modify prp",
    longDesc: "Component changes - modify prp",
  },
  {
    descItem: "MR",
    shortDesc: "MA Dth Reg",
    longDesc: "Maturity Death Register",
  },
  { descItem: "MS", shortDesc: "Mat Stl", longDesc: "Maturity-Settlmnt opt" },
  { descItem: "MX", shortDesc: "Setlmt-End", longDesc: "Setlmt-End" },
  { descItem: "PM", shortDesc: "Prm Matury", longDesc: "Premium Maturity" },
  { descItem: "PO", shortDesc: "Postpone", longDesc: "Contract Postponed" },
  { descItem: "PS", shortDesc: "Proposal", longDesc: "Contract Proposal" },
  { descItem: "PU", shortDesc: "Paid Up", longDesc: "Paid Up Contract" },
  { descItem: "PW", shortDesc: "Wfwd Pndg", longDesc: "Windforward Pending" },
  {
    descItem: "RC",
    shortDesc: "Repudiate",
    longDesc: "Repudiate Death Claim",
  },
  {
    descItem: "RD",
    shortDesc: "Reg Death",
    longDesc: "Registered Death Claim",
  },
  {
    descItem: "RP",
    shortDesc: "Red paidup",
    longDesc: "Reduced Paid Up Contract",
  },
  {
    descItem: "RS",
    shortDesc: "Repd Setlm",
    longDesc: "Repudiation Settlement Option",
  },
  {
    descItem: "SD",
    shortDesc: "Er Sr Appv",
    longDesc: "Early Surrender Approval",
  },
  { descItem: "SR", shortDesc: "Surr Reg", longDesc: "Surrender Register" },
  {
    descItem: "SU",
    shortDesc: "Surrender",
    longDesc: "Contract Surrendered",
  },
  {
    descItem: "TM",
    shortDesc: "Terminate",
    longDesc: "Termination Health Claim",
  },
  {
    descItem: "TR",
    shortDesc: "Terminated",
    longDesc: "Contract Terminated",
  },
  { descItem: "UW", shortDesc: "U/W", longDesc: "Underwriting" },
  { descItem: "VA", shortDesc: "Vest Appr", longDesc: "Vesting Approval" },
  { descItem: "VP", shortDesc: "Vest pendg", longDesc: "Vesting Pending" },
  { descItem: "VR", shortDesc: "Reg Vested", longDesc: "Vesting Registered" },
  { descItem: "WD", shortDesc: "Withdrawn", longDesc: "Contract Withdrawn" },
  { descItem: "AF", shortDesc: "Foreclose", longDesc: "Foreclosure" },
  {
    descItem: "AP",
    shortDesc: "Add prpsl",
    longDesc: "Component change - Add prpsl",
  },
  {
    descItem: "CD",
    shortDesc: "CF DOB Chg",
    longDesc: "Cancelld frm Inception DOB chg",
  },
  { descItem: "CF", shortDesc: "CFI", longDesc: "Cancelled from Inception" },
  { descItem: "CP", shortDesc: "CP", longDesc: "Certificate Printed" },
  {
    descItem: "CR",
    shortDesc: "Regstd HLT",
    longDesc: "Health Claim Resgistred",
  },
  { descItem: "DC", shortDesc: "Declined", longDesc: "Contract Declined" },
  {
    descItem: "DD",
    shortDesc: "Dth Disc R",
    longDesc: "Dth-Discontinued Registered",
  },
  {
    descItem: "DF",
    shortDesc: "Disc Forc",
    longDesc: "Discontinuance Foreclosure",
  },
  {
    descItem: "DH",
    shortDesc: "Death Clm",
    longDesc: "Approved Death Claim",
  },
  {
    descItem: "DI",
    shortDesc: "Dth Disc I",
    longDesc: "Dth - Discontinued Invalid",
  },
  { descItem: "DS", shortDesc: "Er Sur Reg", longDesc: "Early Surrender" },
  { descItem: "DU", shortDesc: "Discont", longDesc: "Policy Discontinued" },
];

const RELATIONSHIPLIST = {
  AP: "Appointee",
  AU: "Aunt  ",
  BR: "Brother",
  BU: "Business",
  CH: "Contingent Policy Holder",
  DA: "Daughter",
  EX: "Executor",
  FA: "Father",
  GD: "Granddaughter",
  GF: "Grandfather",
  GM: "Grandmother",
  GS: "Grandson",
  HU: "Husband",
  MO: "Mother",
  NE: "Nephew",
  NI: "Niece",
  O: "Other",
  OT: "Other",
  SI: "Sister",
  SO: "Son",
  TR: "Trustee ",
  UL: "Uncle",
  WI: "Wife",
};
const billFreq = {
  "01": "Annual",
  "04": "Quarterly ",
  12: "Monthly",
  "00": "Single Pay",
  "02": "Semi Annual",
};

export {
  statusLU,
  messageConstants,
  PREMIUMSTATUSLIST,
  RIDERCODEMAPPING,
  POLICYSTATUSLIST,
  RELATIONSHIPLIST,
  billFreq,
};
